language: javascript
name: factorial
tags: math, recursion, number
# difficulty: easy
description: "Calculate the factorial of a positive integer."
distributes: skeleton.js
test: test.js, Makefile
commands: 
  - validate: "make test"
