language: javascript
name: filter_even
tags: array, filter
# difficulty: easy
description: "Returns a new array with only even numbers."
distributes: skeleton.js
test:
  - test.js
  - Makefile
commands:
  validate: "make test"
