language: javascript
name: fibonacci
tags: math, recursion, sequence
# difficulty: medium
description: "Return the nth Fibonacci number."
distributes: skeleton.js
test:
  - test.js
  - Makefile
commands:
  validate: "make test"
