language: javascript
name: is_palindrome
tags: string, logic
# difficulty: medium
description: "Check if a string is a palindrome (ignoring spaces and case)."
distributes: skeleton.js
test:
  - test.js
  - Makefile
commands:
  validate: "make test"
